### ISSUE TITLE
should we require email verification?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/hapi-register#23]
Should we require people to verify their email address by clicking a link we send to them?
What are the advantages/disadvantages of doing this?

asked by @rub1e on the Gitter chat:
![rub1e-registration-confirmation-question](https://cloud.githubusercontent.com/assets/194400/11561169/67e8df32-99bd-11e5-8aab-163cc845ae30.png)

**Comment by nelsonic** [comment]
@rub1e the reason so many services require you to _confirm_ (_verify_) your email address is two-fold: 
1. Security: you often do not want anonymous people using your application - if they are allowed to use the app without verifying their email you will soon have spam (_once your app is successful..._). 
2. Ensure that you are able to contact people in the future (e.g. to notify them of an update or comment on a piece of their content...) 
3. I creates a "touch point" with the person so they get introduced to your email-feedback-loop

As much as I would like to move _away_ from using email its _still_ the standard way apps interact with people (_until they have a notification feedback-loop..._)

**Comment by rub1e** [comment]
Thanks for this

Yeah, my thinking was that I could live with 1) for now, but 2) is the clincher

Also I'm not doing usernames so email really is the only way

And if I ever add a payment system it'll be totally essential anyway!

**Comment by nelsonic** [comment]
Yeah, I prefer to send people an email _immediately_ rather than ask them to enter their email address twice. if the result of sending that email returns "undelivered" you could notify them in the UI that their email address is invalid. Mandrill gives you this info when you send emails... see: https://travis-ci.org/dwyl/sendemail#L238-L238

Which email service are you using?

**Comment by rub1e** [comment]
ooh - nice - using Mandrill so that's super useful, thanks - that's what I'll go with!

**Comment by nelsonic** [comment]
Mandrill #FTW :wink: 
_Please_ let us know if you need any _specific_ help. 
This is a question we will need to address in our apps/projects so I'm _always_ happy to write code that we can re-use...

**Comment by rub1e** [comment]
Thanks mate! Will have a go and share when done

**Comment by rub1e** [comment]
oh wait, silly of me - it's just

`meteor render whatNelsonicJustSaid`

**Comment by nelsonic** [comment]
lol! `meteor` is win. :stuck_out_tongue_winking_eye:

**Comment by rjmk** [comment]
> I prefer to send people an email immediately rather than ask them to enter their email address twice. if the result of sending that email returns "undelivered" you could notify them in the UI that their email address is invalid.

This is awesome

**Comment by nelsonic** [comment]
(Otherwise) as soon as they confirm their email address by clicking on the link we emailed them, we update their account status to "_confirmed_" and reflect this in the UI :white_check_mark:
