### ISSUE TITLE
License switch

### ISSUE THREAD

**Issue by nilskassube** [nelsonic/hapi-register#30]
Hi,

unfortunately in many circumstances it is not possible to use GPL'ed code. Would it be possible to re-license the project using one of the other licenses like ISC, Apache or MIT?

Best regards and thanks for your efforts!

**Comment by nelsonic** [comment]
Hi @nilskassube, thanks for getting in touch about this package.
we use GPLv2 _because_: https://github.com/dwyl/intellectual-property#q-why-did-you-select-the-gnu-general-public-license-version-2-gpl-v2- it _encourages_ people to share back improvements...
Feel free _expand_ on _why_ you prefer MIT (_is it for a Biz who only use MIT code...?)
We aren't _precious_ about the license, so feel free to send us a Pull Request updating to MIT.
remember to update both the https://github.com/dwyl/hapi-register/blob/master/LICENSE file
and in the [`package.json`](https://github.com/dwyl/hapi-register/blob/e32454a365f0ab994db58e609c51b70e4ddbe13d/package.json#L21) thanks! 👍

**Comment by iteles** [comment]
@nilskassube I would also be very interested if you could share what your use case is that requires re-licensing 😊
