### ISSUE TITLE
which databases should we create examples for? MongoDB? Redis? MySQL? Postgres?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/hapi-register#7]
Which databases should we write examples for?

**Comment by Conorc1000** [comment]
An example for Postgresql would be very helpful.

**Comment by iteles** [comment]
@Conorc1000 :smile:

**Comment by tormod17** [comment]
Firebase seems very popular at the moment

**Comment by nelsonic** [comment]
@Conorc1000 forgot to link to to it: https://github.com/dwyl/hapi-login-example-postgres ...
